import { AppState } from '../../../redux/reducer';

export const loadingEmployeeSelector = (state: AppState) => state.employee.loadingEmployee;
export const nextPageEmployeeSelector = (state: AppState) => state.employee.nextPage;
export const prevPageEmployeeSelector = (state: AppState) => state.employee.prevPage;
export const firstPageEmployeeSelector = (state: AppState) => state.employee.firstPage;
export const lastPageEmployeeSelector = (state: AppState) => state.employee.lastPage;
export const listPageEmployeeSelector = (state: AppState) => state.employee.listPage;
export const totalPageEmployeeSelector = (state: AppState) => state.employee.totalPage;
export const currentPageEmployeeSelector = (state: AppState) => state.employee.currentPage;
export const fromPageEmployeeSelector = (state: AppState) => state.employee.fromPage;
export const toPageEmployeeSelector = (state: AppState) => state.employee.toPage;
export const totalEmployeeSelector = (state: AppState) => state.employee.totalEmployee;
export const marriageEmployeeSelector = (state: AppState) => state.managerEmployee.marriage;
export const positionEmployeeSelector = (state: AppState) => state.managerEmployee.position;
export const departmentEmployeeSelector = (state: AppState) => state.managerEmployee.department;
export const defaultSalaryEmployeeSelector = (state: AppState) => state.managerEmployee.defaultSalary;
export const benefitEmployeeSelector = (state: AppState) => state.managerEmployee.benefit;
export const gradeEmployeeSelector = (state: AppState) => state.managerEmployee.grade;
export const employeeSelector = (state: AppState) => state.employee.employee;
export const multipleUploadTableSelector = (state: AppState) => state.managerEmployee.multipleUpload;
export const uploadTableSelector = (state: AppState) => state.managerEmployee.upload;
export const currentEmpolyeeSelector = (state: AppState) => state.managerEmployee.currentEmployee;
export const listDeleteUpdateSelector = (state: AppState) => state.managerEmployee.listDeleteUpdate;
export const loadingAddOrUpdateSelector = (state: AppState) => state.managerEmployee.loadingAddOrUpdate;
export const getStateDeleteEmployeeSelector = (state: AppState) => state.managerEmployee.deleteSuccess;
