const icons = {
  logo: require('./Rectangle 4.svg').default,
  en: require('./image 1.svg').default,
  arrowDown: require('./Vector.svg').default,
  nav1: require('./iconnav1.svg').default,
  nav2: require('./iconnav2.svg').default,
  nav3: require('./iconnav3.svg').default,
  nav4: require('./iconnav4.svg').default,
  nav5: require('./iconnav5.svg').default,
  nav6: require('./iconnav6.svg').default,
  nav7: require('./iconnav7.svg').default,
  btnAdd: require('./btn-add.svg').default,
  btnDelete: require('./btn-delete.svg').default,
  success: require('./check-circle.svg').default,
  dager: require('./alert-triangle.svg').default,
  warn: require('./alert-circle.svg').default,
  info: require('./info.svg').default,
  loading: require('./loader.svg').default,
};
export default icons;
